history:
    resource: "@HrisRecordsBundle/Controller/HistoryController.php"
    type: annotation

record:
    resource: "@HrisRecordsBundle/Controller/RecordController.php"
    type: annotation

training:
    resource: "@HrisRecordsBundle/Controller/TrainingController.php"
    type: annotation

validation_run:
    resource: "@HrisRecordsBundle/Controller/ValidationRunController.php"
    type: annotation

validation_result:
    resource: "@HrisRecordsBundle/Controller/ValidationRunController.php"
    type: annotation