parameters:
#    hris_message.example.class: Hris\MessageBundle\Example

services:
#    hris_message.example:
#        class: %hris_message.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
