help_helpcentre_chapter:
    resource: "@HrisHelpCentreBundle/Controller/ChapterController.php"
    type: annotation
    
help_helpcentre_topic:
    resource: "@HrisHelpCentreBundle/Controller/TopicController.php"
    type: annotation

help_helpcentre_helpcentre:
    resource: "@HrisHelpCentreBundle/Controller/HelpCentreController.php"
    type: annotation