import_export_history:
    resource: "@HrisImportExportBundle/Controller/HistoryController.php"
    type: annotation

import_export_export:
    resource: "@HrisImportExportBundle/Controller/ExportController.php"
    type: annotation

import_export_exportmetadata:
    resource: "@HrisImportExportBundle/Controller/ExportMetadataController.php"
    type: annotation

import_export_import:
    resource: "@HrisImportExportBundle/Controller/ImportController.php"
    type: annotation