dhis_data_integration:
    resource: "@HrisIntergrationBundle/Controller/DHISDataConnectionController.php"
    type: annotation

tiis_data_integration:
    resource: "@HrisIntergrationBundle/Controller/TIISDataConnectionController.php"
    type: annotation
