parameters:
#    hris_target.example.class: Hris\IndicatorBundle\Target

services:
    hris_target.configure_menu_listener:
            class: Hris\IndicatorBundle\EventListener\ConfigureMenuListener
            tags:
                - { name: kernel.event_listener, event: hris_target.menu_configure, method: onMenuConfigure }